# For running app + dependencies like Postgres, Redis
# Define services for app, db,
version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: container/Dockerfile
    restart: always
    ports:
      - "8082:8080"
      - "8081:8081"
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - .:/app
    environment:
      - GO111MODULE=on
    command: /server

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"  # for management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  nginx:
    image: nginx:latest
    ports:
      - "80:80"        # You access NGINX via localhost:80
    volumes:
      - ./container/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server         # NGINX should wait for Go app
